package com.betterlocatorbar.mixin;

import com.betterlocatorbar.config.BLBConfig;
import com.betterlocatorbar.renderer.PlayerHeadRenderer;
import net.minecraft.client.MinecraftClient;
import net.minecraft.client.gui.DrawContext;
import net.minecraft.client.network.ClientPlayerEntity;
import net.minecraft.client.network.PlayerListEntry;
import net.minecraft.client.render.RenderTickCounter;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

import java.util.List;

/**
 * Intercepts the vanilla locator bar rendering to optionally replace colored
 * dot icons with player skin head icons.
 *
 * <p>In 1.21.11 the locator bar was moved out of InGameHud into its own
 * class: {@code net.minecraft.client.gui.contextualbar.LocatorBarRenderer}.
 * The render method (Mojang name: {@code render}) takes a GuiGraphics /
 * DrawContext and a DeltaTracker / RenderTickCounter.</p>
 *
 * <p>We use {@code remap = false} and the intermediary / Mojang method
 * descriptor so the injection works without a refMap at runtime.</p>
 */
@Mixin(targets = "net.minecraft.client.gui.contextualbar.LocatorBarRenderer")
public class LocatorBarRendererMixin {

    /**
     * Injected at HEAD of {@code render} — cancels vanilla dot rendering and
     * replaces it with our player-head bar when the feature is enabled.
     *
     * <p>The method descriptor uses Mojang class names; Fabric remaps them to
     * intermediary at runtime via the mod's refMap generated by Loom.</p>
     */
    @Inject(
            method = "render",
            at = @At("HEAD"),
            cancellable = true,
            remap = true
    )
    private void blb$replaceLocatorDots(DrawContext context, RenderTickCounter tickCounter, CallbackInfo ci) {
        if (!BLBConfig.get().showPlayerHeads) return;

        MinecraftClient mc = MinecraftClient.getInstance();
        if (mc == null || mc.world == null || mc.player == null) return;

        // Cancel vanilla rendering — we draw ourselves
        ci.cancel();

        renderHeadLocatorBar(context, mc);
    }

    private void renderHeadLocatorBar(DrawContext context, MinecraftClient mc) {
        if (mc.getNetworkHandler() == null) return;

        ClientPlayerEntity localPlayer = mc.player;
        if (localPlayer == null) return;

        // Collect all tracked players (except self)
        List<PlayerListEntry> trackedPlayers = mc.getNetworkHandler()
                .getPlayerList()
                .stream()
                .filter(e -> e.getProfile() != null
                        && !e.getProfile().id().equals(localPlayer.getUuid()))
                .toList();

        if (trackedPlayers.isEmpty()) return;

        // Layout constants
        int screenWidth = mc.getWindow().getScaledWidth();
        int screenHeight = mc.getWindow().getScaledHeight();

        float headScale = BLBConfig.get().headScale;
        int headSize = Math.max(8, (int) (9 * headScale));
        int barY = screenHeight - 32 - headSize;

        int barWidth = Math.min(screenWidth - 40, trackedPlayers.size() * (headSize + 4));
        int startX = (screenWidth - barWidth) / 2;

        for (int i = 0; i < trackedPlayers.size(); i++) {
            PlayerListEntry entry = trackedPlayers.get(i);

            int iconX;
            if (trackedPlayers.size() == 1) {
                iconX = startX + (barWidth / 2) - (headSize / 2);
            } else {
                iconX = startX + i * (barWidth / Math.max(1, trackedPlayers.size() - 1))
                        - (headSize / 2);
            }
            iconX = Math.clamp(iconX, 0, screenWidth - headSize);

            PlayerHeadRenderer.drawPlayerHead(context, entry, iconX, barY, headSize, 1.0f);

            if (BLBConfig.get().showNameTag) {
                PlayerHeadRenderer.drawPlayerName(context, entry,
                        iconX + headSize / 2, barY + headSize);
            }
        }
    }
}
